[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[terminal.shell]
program = "/home/gt/.local/bin/tmuxtart"

[env]
TERM = "xterm-256color"

[font]
size = 10
# normal = { family = "JetBrains Mono NF" }
normal = { family = "Maple Mono NF" }
# offset.y = 0

[window]
padding = { x = 4, y = 2 }
startup_mode = "Maximized"
decorations = "None"
# opacity = 0.97

[colors]
primary.background = '#1b1919'

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"
